#!/bin/bash
set +e
# 执行命令并将结果存储到变量中

#原作者：酷安水竹闲士x 部分By: JARK006
las=0
pre=1
las_num=-1
num=0
temp_file='/data/local/mem_app_test'
touch /data/local/mem_app_test0
touch /data/local/mem_app_test1
curr_index=$las
#echo -e "\e[?25"
echo -e "\e[93m"
echo -e "\e[2J"
echo -e "\033[1;5H\033[31;"
function necho(){
    #echo -e "\e[$2;1H$1"
    echo $1
}

function get_mem_info(){
    # 获取内存信息
    mem_info=$(cat /proc/meminfo)
    
    # 提取总内存大小
    mem_total=$(echo "$mem_info" | grep "MemTotal" | awk '{print $2}')
    
    # 提取可用内存大小
    mem_available=$(echo "$mem_info" | grep "MemAvailable" | awk '{print $2}')
    
    # 计算内存占用百分比
    mem_usage=$(awk "BEGIN {printf \"%.2f\", 100-($mem_available / $mem_total) * 100}")
}
function freezen_type()
{
echo "==============[ 内存管理状态 ]=============="
    if [ $han1 = 'running' ]; then
        echo "✔️已开启 $ofreezeinfo墓碑"
    else
        echo "❌未开启 OFreezer墓碑"
    fi
    if [ -e /sys/fs/cgroup/uid_0/cgroup.freeze ]; then
        echo "✔️已挂载 FreezerV2(UID)"
    else
        echo "❌不支持 FreezerV2(UID)"
    fi
    
    if [[ -e /sys/fs/cgroup/frozen/cgroup.freeze ]] && [[ -e /sys/fs/cgroup/unfrozen/cgroup.freeze ]]; then
        echo "✔️已挂载 FreezerV2(FROZEN)"
    else
        echo "❌不支持 FreezerV2(frozen)"
    fi
    
    if [ -e /sys/fs/cgroup/freezer/perf/frozen/freezer.state ]; then
        echo "✔️已挂载 FreezerV1(FROZEN)"
    fi
    
}
function get_power(){
    Battry_voltage=`cat /sys/class/power_supply/battery/voltage_now`
    Battery_currrnt=`cat /sys/class/power_supply/battery/current_now`
    ((Battry_voltage/=1000))
    ((power=Battery_currrnt*Battry_voltage/1000))
}

function update_mem_app_list(){
    if [ $curr_index -eq $las ];then
        curr_index=$pre
    else curr_index=$las
    fi
    ps_info_line=$(ps -ef -o uid,command,args | grep /system/bin/app_process64 | grep -v -e grep -e system_server -e : -e webview_zygote -e zygote64|awk '{print $1,$3}'|tee $temp_file$curr_index)
    #echo $ps_info
    uids=$(awk '{print $1}' $temp_file$curr_index)
    num=$(echo $uids|wc -w )
    status=$(ps -A  | grep -E "refrigerator|do_freezer|signal" | grep -v ':'| grep -v 'su'| awk '{print $6 " " $9}')
    status=${status//"__refrigerator"/"❄️FreezerV1冻结中:"}
    status=${status//"do_freezer_trap"/"❄️FreezerV2冻结中:"}
    status=${status//"do_signal_stop"/"🧊SIGSTOP冻结中:"}
    status=${status//"get_signal"/"❄️不完整V2冻结中:"}
    #echo "${#status}"
    fe=$(echo $status|wc -w )
    freezed=0
    ((freezed=fe/2))
}
function freezeinfov2()
{
    v1Info=$(mount | grep freezer | awk '{print "✔️已挂载 FreezerV1: ",$3}')
    if [ ${#v1Info} -gt 2 ]; then
        echo "$v1Info"
    fi
    if [ ${#status} -gt 2 ]; then
echo "==============[ 应用冻结状态 ]==============
$status
"
    else
        echo "暂无冻结状态的进程"
    fi
}
function freezeinfo()
{
    ps_info=($ps_info_line)
    i=0;
    j=1;
    size=${#ps_info[@]}
    while true; do
      
      #echo "${ps_info[@]}"
      line="${ps_info[$i]} ${ps_info[$j]}"
      #echo $line $i $j
      uid=$(echo "$line" | awk '{print $1}')
      name=$(echo "$line" | awk '{print $2}')
    
      freeze_file="/sys/fs/cgroup/uid_$uid/cgroup.freeze"
      freeze_value=$(cat "$freeze_file")
    
      if [ "$freeze_value" -eq 1 ] && [[ "$name" == com.tencent.* ]]; then
        echo "腾讯系应用：$name处于冻结中"
      fi
      if [ "$uid" -gt 10000 ]; then
        echo "$line 是第三方应用"
        echo 1 >$freeze_file
      fi
      i=$((i+2))
      j=$((j+2))
    if [ $j -gt $size ]; then
    break
    fi
    done
}
rm -rf ./mem_app.log
count=0
ofreezeinfo=$(grep module-version /data/oplus/os/bpm/sys_elsa_config_list.xml|/bin/awk -F'[<>]' '/<module-version>/ {getline; print $3}')
while
do
   # echo -e "\e[2J"
    #echo -e "\033[1;5H\033[31;"
    echo "###################" >>./mem_app.log
    han1=$(getprop init.svc.hans)
    han2=$(getprop persist.vendor.enable.hans)
    update_mem_app_list
    get_power
    get_mem_info
    sleep 1
    echo -e "\e[2J"
    echo -e "\033[1;5H\033[31;"
    freezen_type
    necho "当前实际功率是:$power mW" 5
    necho "MemAvailable: $((mem_available/1024)) MB"  6
    necho "内存占用百分比: ${mem_usage}%" 7
    necho "当前app数为：${num}" 8
    necho "当前被墓碑APP数：${freezed}" 11
    if [ ${#status} -gt 2 ]; then
echo "==============[ 应用冻结状态 ]==============
$status
"
    else
        echo "暂无冻结状态的进程"
    fi
    
    diff_app=$(sort $temp_file$las $temp_file$pre | uniq -u)
    ((temp=num-count))
    echo "MemAvailable: $((mem_available/1024)) MB" >>./mem_app.log
    echo "内存占用百分比: ${mem_usage}%" >>./mem_app.log
    echo "当前app数为：${num}" >>./mem_app.log
    if [ $count -eq 0 ];then
        count=$num
        continue
    elif [ $temp -gt 0 ];then
        necho "新增${temp}个App: " 9
        necho "${diff_app}" 10
        echo "新增${temp}个App: " >>./mem_app.log
        echo ${diff_app} >>./mem_app.log
        count=${num}
        continue
    elif [ $temp -lt 0 ];then
        necho "减少${temp}个App：" 9
        necho "${diff_app}" 10
        echo "减少${temp}个App：" >>./mem_app.log
        echo ${diff_app} >>./mem_app.log
        count=${num}
    fi
    #freezeinfo
    #cat /sys/block/zram0/hybridswap_enable
done
